export const PATH_URL_DATA = {
    urlHome: 'home',
    urlVacaciones: 'vacaciones',
    urlUsuarios: 'usuarios',
    urlPeriodos: 'periodos',
    urlBandejaVacaciones: 'bandeja',
    urlRegistrarVacaciones: 'registrar',
    urlReporte: 'reporte',
    urlReporteHistorico: 'reporte-historico',
    urlReporteSolicitudes: 'reporte-solicitudes',
    urlDetalleVacaciones: 'solicitud/:solic',
    urlInterrupcionVacaciones: 'interrumpir-solicitud/:solic',
    urlReprogramarVacaciones : 'reprogramar-solicitud/:solic',
    urlSolicitudesPendientes : 'solicitudes-pendientes',
    urlSolicitudesPendientesDetalle : 'solicitudes-pendientes/:solic',
    urlSolicitudesPendientesGrh : 'solicitudes-pendientes-grh',
    urlSolicitudesPendientesDetalleGrh : 'solicitudes-pendientes-grh/:solic',
    ulrError: 'error',
    urlDefault: '',
    urlDefault2: '**'
};